pipeline {
    agent {
        docker {
            image 'ngacareer/alpine-nodejs'
            args '-p 3000:3000'
        }
    }
    environment { 
        CI = 'true'
    }
    
  stages {
        
    stage('Git') {
      steps {
        git 'https://github.com/ngacareer/jenkins-pipeline-nodejs.git'
      }
    }
     
    stage('Build') {
      steps {
        sh 'npm install'
         sh '<<Build Command>>'
      }
    }  
    
            
    stage('Test') {
      steps {
        sh 'node test'
      }
    }
  }    
}
